# Generated by Django 6.0.1 on 2026-02-03 11:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('ssn', models.CharField(db_index=True, max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_reference', models.CharField(db_index=True, max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('IN_COLLECTION', 'In Collection'), ('PAID_IN_FULL', 'Paid In Full')], max_length=20)),
                ('consumers', models.ManyToManyField(related_name='accounts', to='collection.consumer')),
            ],
        ),
    ]
